export const ErrorMessages = {
  AUTH: {
    TOKEN_NOT_PROVIDED: 'AUTH_TOKEN_NOT_PROVIDED',
    SESSION_INACTIVE: 'AUTH_SESSION_INACTIVE',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    ACCESS_DENIED_ROLE: 'AUTH_ACCESS_DENIED_ROLE',
    ACCESS_DENIED_SUPER_ADMIN: 'AUTH_ACCESS_DENIED_SUPER_ADMIN',
    INACTIVE_ACCOUNT: 'AUTH_INACTIVE_ACCOUNT',
    ADMIN_EXISTS: 'AUTH_ADMIN_EXISTS',
    ROLE_EXISTS: 'AUTH_ROLE_EXISTS',
    ROLE_REQUIRED: 'AUTH_ROLE_REQUIRED',
    ROLE_NOT_FOUND: 'AUTH_ROLE_NOT_FOUND',
    SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
    SESSION_REVOKE_UNAUTHORIZED: 'AUTH_SESSION_REVOKE_UNAUTHORIZED',
    MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
    INVALID_OTP: 'AUTH_INVALID_OTP',
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    FAILED_USER_RESOLVE: 'AUTH_FAILED_USER_RESOLVE',
    CURRENT_TOKEN_MISSING: 'AUTH_CURRENT_TOKEN_MISSING',
    OTP_SEND_FAILED: 'AUTH_OTP_SEND_FAILED',
    OTP_VERIFY_FAILED: 'AUTH_OTP_VERIFY_FAILED',
    PROFILE_UPDATE_FAILED: 'AUTH_PROFILE_UPDATE_FAILED'
  },
  CHAT: {
    CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
    CHAT_ID_REQUIRED: 'CHAT_ID_REQUIRED',
    FETCHED_FAILED: 'CHAT_FETCHED_FAILED',
    MESSAGES_FETCHED_FAILED: 'CHAT_MESSAGES_FETCHED_FAILED',
    CREATED_FAILED: 'CHAT_CREATED_FAILED',
    UPDATED_FAILED: 'CHAT_UPDATED_FAILED',
    MESSAGE_UPDATED_FAILED: 'MESSAGE_UPDATED_FAILED',
    MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
    DELETED_FAILED: 'CHAT_DELETED_FAILED'
  },
  SYSTEM: {
    SERVER_ERROR: 'SYSTEM_SERVER_ERROR',
    DB_FAILED: 'SYSTEM_DB_FAILED'
  },
  SETTING: {
    RETRIEVED_FAILED: 'SETTING_RETRIEVED_FAILED',
    UPDATED_FAILED: 'SETTING_UPDATED_FAILED'
  },
  ADMIN: {
    LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
    CREATED_FAILED: 'ADMIN_CREATED_FAILED',
    RETRIEVED_FAILED: 'ADMIN_RETRIEVED_FAILED',
    UPDATED_FAILED: 'ADMIN_UPDATED_FAILED',
    DELETED_FAILED: 'ADMIN_DELETED_FAILED',
    NOT_FOUND: 'ADMIN_NOT_FOUND'
  },
  ROLE: {
    CREATED_FAILED: 'ROLE_CREATED_FAILED',
    RETRIEVED_FAILED: 'ROLE_RETRIEVED_FAILED',
    NOT_FOUND: 'ROLE_NOT_FOUND',
    UPDATED_FAILED: 'ROLE_UPDATED_FAILED',
    DELETED_FAILED: 'ROLE_DELETED_FAILED'
  },
  SESSION: {
    RETRIEVED_FAILED: 'SESSION_RETRIEVED_FAILED',
    REVOKED_FAILED: 'SESSION_REVOKED_FAILED'
  },
  USER: {
    CREATED_FAILED: 'USER_CREATED_FAILED',
    RETRIEVED_FAILED: 'USER_RETRIEVED_FAILED',
    UPDATED_FAILED: 'USER_UPDATED_FAILED',
    DELETED_FAILED: 'USER_DELETED_FAILED',
    NOT_FOUND: 'USER_NOT_FOUND',
    EXISTS: 'USER_EXISTS'
  }
};

export const SuccessMessages = {
  AUTH: {
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    OTP_SENT: 'AUTH_OTP_SENT',
    OTP_VERIFIED: 'AUTH_OTP_VERIFIED',
    PROFILE_UPDATED: 'AUTH_PROFILE_UPDATED'
  },
  ROLE: {
    CREATED: 'ROLE_CREATED',
    RETRIEVED: 'ROLE_RETRIEVED',
    UPDATED: 'ROLE_UPDATED',
    DELETED: 'ROLE_DELETED'
  },
  SESSION: {
    RETRIEVED: 'SESSION_RETRIEVED',
    REVOKED: 'SESSION_REVOKED',
    MY_SESSIONS_RETRIEVED: 'SESSION_MY_SESSIONS_RETRIEVED',
    OTHER_REVOKED: 'SESSION_OTHER_REVOKED'
  },
  CHAT: {
    FETCHED: 'CHAT_FETCHED',
    MESSAGES_FETCHED: 'CHAT_MESSAGES_FETCHED',
    CREATED: 'CHAT_CREATED',
    UPDATED: 'CHAT_UPDATED',
    MESSAGE_UPDATED: 'MESSAGE_UPDATED',
    DELETED: 'CHAT_DELETED'
  },
  SETTING: {
    RETRIEVED: 'SETTING_RETRIEVED',
    UPDATED: 'SETTING_UPDATED'
  },
  ADMIN: {
    CREATED: 'ADMIN_CREATED',
    RETRIEVED: 'ADMIN_RETRIEVED',
    UPDATED: 'ADMIN_UPDATED',
    DELETED: 'ADMIN_DELETED'
  },
  USER: {
    CREATED: 'USER_CREATED',
    RETRIEVED: 'USER_RETRIEVED',
    UPDATED: 'USER_UPDATED',
    DELETED: 'USER_DELETED'
  }
};
